name: beesPlugin
version: '1.0-SNAPSHOT'
main: org.maks.beesPlugin.BeesPlugin
api-version: '1.20'
softdepend: [Vault]
commands:
  hive:
    description: Manage hives
    permission: beesplugin.hive
    usage: /hive
  infuse:
    description: Infuse a larva
    permission: beesplugin.infuse
    usage: /infuse
